### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by svnpenn** [jfet97/strawberry#9]
What is the reason why someone would want to use this - i went here

http://jfet97.github.io/strawberry

and it tells me:

1. what it is: flexbox based CSS micro-framework

2. how to install it

3. how small it is

4. create Flexbox-based layouts in few lines of code - this is strange because can you already do that with regular CSS?

maybe some examples on that page would be helpful - to demonstrate why people would want to use this

**Comment by jfet97** [comment]
Yes I am working on the responsive layer of this framework and I will add some examples. Sorry about that but I started this project last week and there is so much work to do.
The powerful of this framework is let you create nexted flexboxes really fast (you can easily create nested flexbox from the container with only one class, but there is more you can do instead of using vanilla CSS) and soon you could do great thing using responsive.
